"use client";
import {useEffect,useState} from "react";

type ApDocument={id:string;filename:string;status:string;created_at:string;error_message?:string|null;extraction?:Record<string,unknown>|null};
export default function InvoiceIntake(){
 const [documents,setDocuments]=useState<ApDocument[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{try{const r=await fetch("/api/ap/documents",{cache:"no-store"}),j=await r.json() as {documents?:ApDocument[]};setDocuments(j.documents||[])}catch{setDocuments([])}};
 useEffect(()=>{void load()},[]);
 const submit=async()=>{if(!file)return;setBusy(true);setMessage("");const form=new FormData();form.set("invoice",file);try{const r=await fetch("/api/ap/invoices/extract",{method:"POST",body:form}),j=await r.json() as {ok?:boolean;message?:string};setMessage(j.message||`HTTP ${r.status}`);if(j.ok){setFile(null);await load()}}catch{setMessage("The invoice could not be submitted.")}finally{setBusy(false)}};
 return <section className="panel"><header><h2>New invoice transactions</h2></header><div className="invoice-intake"><div className="info security"><b>Human-reviewed AP agent · evaluation limited</b> The agent extracts visible facts only. It never calculates tax, posts entries, changes vendor bank details, or invents missing evidence.</div><div className="upload-row"><label>Supplier invoice pack<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={!file||busy} onClick={submit}>{busy?"Reading invoice…":"Extract for review"}</button><button disabled={busy} onClick={load}>Refresh queue</button></div>{message&&<div className="result" role="status">{message}</div>}<div className="invoice-queue">{documents.length===0?<div className="empty"><b>No invoice documents received</b><p>Upload a real invoice pack; no examples are displayed.</p></div>:documents.map(doc=><article className="review-card" key={doc.id}><header><div><b>{doc.filename}</b><small>{new Date(doc.created_at).toLocaleString()}</small></div><span className={`chip ${doc.status==="extracted"?"ok":"neutral"}`}>{doc.status.replaceAll("_"," ")}</span></header>{doc.error_message&&<p className="error-text">{doc.error_message}</p>}{doc.extraction&&<dl>{Object.entries(doc.extraction).filter(([key,value])=>value!==null&&value!==""&&!Array.isArray(value)&&key!=="confidence").map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{String(value)}</dd></div>)}</dl>}<p className="review-note">Review required before any accounting proposal or Odoo draft can be created.</p></article>)}</div></div></section>
}
