"use client";
import {useEffect,useMemo,useState} from "react";
import "./handoff.css";
import {nextCampaign,type CampaignPolicy} from "./lib/campaign-engine";

type Lang="en"|"fr"; type Route="control"|"cfo"|"controller"|"planningManager"|"agents"|"ap"|"ar"|"treasury"|"assets"|"gl"|"tax"|"planning"|"pricing"|"value"|"policies"|"campaigns"|"journals"|"approvals"|"documents"|"erp"|"audit"|"reports"|"admin"|"settings";
type Connection={id:string;name:string;endpoint:string;database:string;login:string;company:string;protocol:string;updatedAt:string;lastSyncAt?:string|null;connected:true};
const text={
 en:{tag:"AI-assisted finance operations",tenant:"Tenant",entity:"Legal entity",sync:"Last sync",command:"Command",reporting:"Financial Reporting Agents",planningAgents:"Financial Planning Agents",operations:"Operations",system:"System",control:"Control Room",cfo:"CFO",controller:"Financial Controller",planningManager:"Financial Planning Manager",agents:"Agent overview",ap:"AP Accountant",ar:"AR Accountant",treasury:"Treasury Accountant",assets:"Fixed Assets Accountant",gl:"General Ledger Accountant",tax:"Tax Accountant",planning:"Financial Planning Analyst",pricing:"Pricing Analyst",value:"Value for Money Analyst",policies:"Policies",campaigns:"Payment Campaigns",journals:"Journal Centre",approvals:"Approvals",documents:"Documents",erp:"ERP Connections",audit:"Audit Trail",reports:"Reports",admin:"Admin",settings:"Tenant Settings",empty:"No verified ERP data available",emptyHelp:"Refresh after connecting Odoo. The application never displays invented records.",refresh:"Refresh data",refreshAll:"Sync entire application",connect:"Connect Odoo",save:"Save connection",test:"Test connection",saved:"Connection saved securely",responsibilities:"Responsibilities",provision:"Agent provisioning",companies:"Companies",users:"Users"},
 fr:{tag:"Opérations financières assistées par IA",tenant:"Client",entity:"Entité juridique",sync:"Dernière synchronisation",command:"Pilotage",reporting:"Agents de reporting financier",planningAgents:"Agents de planification financière",operations:"Opérations",system:"Système",control:"Centre de pilotage",cfo:"Directeur financier",controller:"Contrôleur financier",planningManager:"Responsable planification financière",agents:"Vue des agents",ap:"Comptable fournisseurs",ar:"Comptable clients",treasury:"Comptable trésorerie",assets:"Comptable immobilisations",gl:"Comptable général",tax:"Comptable fiscal",planning:"Analyste planification financière",pricing:"Analyste tarification",value:"Analyste rapport qualité-prix",policies:"Politiques",campaigns:"Campagnes de paiement",journals:"Centre des écritures",approvals:"Approbations",documents:"Documents",erp:"Connexions ERP",audit:"Piste d’audit",reports:"Rapports",admin:"Administration",settings:"Paramètres du client",empty:"Aucune donnée ERP vérifiée disponible",emptyHelp:"Actualisez après avoir connecté Odoo. L’application n’affiche jamais de données inventées.",refresh:"Actualiser les données",refreshAll:"Synchroniser toute l’application",connect:"Connecter Odoo",save:"Enregistrer la connexion",test:"Tester la connexion",saved:"Connexion enregistrée de manière sécurisée",responsibilities:"Responsabilités",provision:"Provisionnement des agents",companies:"Sociétés",users:"Utilisateurs"}
};
const nav=[{group:"command",items:["control","cfo","controller","planningManager","policies"]},{group:"reporting",items:["agents","ap","ar","treasury","assets","gl","tax"]},{group:"planningAgents",items:["planning","pricing","value"]},{group:"operations",items:["campaigns","journals","approvals","documents"]},{group:"system",items:["erp","audit","reports","admin","settings"]}] as const;
const responsibility:Record<string,string>={cfo:"Own finance strategy, capital allocation, financing, governance and executive reporting.",controller:"Supervise financial reporting, close, accounting policy, controls and all reporting agents.",planningManager:"Lead budgets, forecasts, scenarios, performance management and all planning agents.",ap:"Process vendor invoices, perform three-way matching, propose coding, maintain AP ageing and submit draft AP journals.",ar:"Manage customer billing, receipts, credit control, collections and AR ageing.",treasury:"Manage liquidity, bank journals, reconciliations, payment campaigns and cash forecasting.",assets:"Maintain the fixed-asset register, capitalisation, depreciation, disposals and reconciliations.",gl:"Own the general ledger, period close, reconciliations, draft journals and financial statements.",tax:"Determine tax treatment, prepare VAT and withholding records, monitor filings and flag exceptions.",planning:"Build budgets and forecasts, analyse variances, maintain models and management dashboards.",pricing:"Develop pricing models, analyse margin and elasticity, and support pricing approvals.",value:"Perform cost-benefit and value-for-money assessments and track realised savings."};
function Empty({t}:{t:typeof text.en}){return <div className="empty"><span>↻</span><b>{t.empty}</b><p>{t.emptyHelp}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><header><h2>{title}</h2></header>{children}</section>}
function Kpis({t,labels}:{t:typeof text.en;labels:string[]}){return <div className="kpis">{labels.map(label=><article className="glass-card" key={label}><small>{label}</small><b>—</b><p>{t.emptyHelp}</p></article>)}</div>}

export default function Home(){
 const [lang,setLang]=useState<Lang>("en"),[route,setRoute]=useState<Route>(()=>{const saved=typeof window!=="undefined"?window.location.hash.slice(1):"";return nav.some(g=>g.items.includes(saved as never))?saved as Route:"control"}),[connection,setConnection]=useState<Connection|null>(null),[lastSync,setLastSync]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""); const t=text[lang];
 const [policy]=useState<CampaignPolicy>({campaignDays:[13,25],horizonDays:4,weekendRule:"prev",version:1}); const next=useMemo(()=>nextCampaign(new Date(),policy),[policy]);
 const load=async()=>{try{const r=await fetch("/api/erp-connections",{cache:"no-store"}),j=await r.json() as {connection:Connection|null};setConnection(j.connection);if(j.connection?.lastSyncAt)setLastSync(j.connection.lastSyncAt)}catch{setConnection(null)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{window.history.replaceState(null,"",`#${route}`)},[route]);
 const sync=async()=>{setBusy(true);try{const r=await fetch("/api/sync",{method:"POST"}),j=await r.json() as {ok?:boolean;message?:string;refreshedAt?:string};setNotice(j.message||`HTTP ${r.status}`);if(j.ok&&j.refreshedAt)setLastSync(j.refreshedAt)}catch{setNotice("Synchronisation failed.")}finally{setBusy(false)}};
 const go=(id:Route)=>{setRoute(id);window.history.replaceState(null,"",`#${id}`)}; const name=(id:Route)=>t[id]||id; const tenant=connection?.company||"Default tenant";
 return <div className="app"><header className="top"><div className="brand"><i/><span><b>My Accountant</b><small>{t.tag}</small></span></div><div className="selectors"><label>{t.tenant}<select><option>{tenant}</option></select></label><label>{t.entity}<select><option>{connection?.company||"No entity connected"}</option></select></label><div className="lang"><button aria-pressed={lang==="en"} onClick={()=>setLang("en")}>EN</button><button aria-pressed={lang==="fr"} onClick={()=>setLang("fr")}>FR</button></div></div><div className="context"><span className={`chip ${connection?"ok":"neutral"}`}>{connection?`● ${connection.name}`:"○ ERP not connected"}</span><span>{t.sync} {lastSync?new Date(lastSync).toLocaleString():"—"}</span></div></header><div className="body"><nav className="side">{nav.map(group=><section key={group.group}><h3>{t[group.group]}</h3>{group.items.map(id=><button key={id} aria-current={route===id?"page":undefined} onClick={()=>setRoute(id)}><i>{id.slice(0,2).toUpperCase()}</i>{name(id)}</button>)}</section>)}</nav><main><div className="page-head"><div><small>{t.command} / {name(route)}</small><h1>{name(route)}</h1><p>{t.tag}</p></div><div className="head-actions"><button onClick={()=>setRoute("erp")}>{t.connect}</button><button className="primary" disabled={!connection||busy} onClick={sync}>{busy?"…":t.refresh}</button></div></div><RouteBody route={route} t={t} connection={connection} onSaved={c=>{setConnection(c);setNotice(t.saved)}}/></main></div>{notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>
}
function RouteBody({route,t,connection,onSaved}:{route:Route;t:typeof text.en;connection:Connection|null;onSaved:(c:Connection)=>void}){
 if(route==="erp")return <>{connection&&<div className={`connection-banner ${connection.lastSyncAt?"connected":"saved"}`}><b>{connection.lastSyncAt?"● Connected & synced":"◐ Connection saved"}</b><span>{connection.name} · {connection.company}{connection.lastSyncAt?` · Last sync ${new Date(connection.lastSyncAt).toLocaleString()}`:" · Test the saved connection to synchronise"}</span></div>}<ErpWizard t={t} existing={connection} onSaved={onSaved}/></>;
 if(route==="cfo"||route==="controller"||route==="planningManager"||route==="agents")return <Hierarchy t={t} focus={route}/>;
 if(route==="admin")return <AdminWorkspace t={t}/>;
 const labels:Record<string,string[]>={control:["Approvals awaiting","Draft journals in ERP","Cash position","Open anomalies"],ap:["Unposted AP journals","AP ageing","Invoices received by email","Invoices awaiting processing"],ar:["Unposted AR journals","AR ageing","Receipts awaiting allocation","Overdue customers"],treasury:["Cash position","Bank journals","Unreconciled transactions","Payments awaiting approval"]};
 return <><Kpis t={t} labels={labels[route]||[nameFor(t,route),"Open items","Exceptions","Ready"]}/><Panel title={nameFor(t,route)}><Empty t={t}/></Panel></>
}
function nameFor(t:typeof text.en,id:Route){return t[id]||id}
function Hierarchy({t,focus}:{t:typeof text.en;focus:Route}){const reporting:Route[]=["ap","ar","treasury","gl","tax"],planning:Route[]=["planning","pricing","value"];return <div className="org"><AgentCard id="cfo" t={t} featured={focus==="cfo"}/><div className="org-branches"><section><AgentCard id="controller" t={t} featured={focus==="controller"}/><h3>{t.reporting}</h3><div className="agent-grid">{reporting.map(id=><AgentCard key={id} id={id} t={t}/>)}</div></section><section><AgentCard id="planningManager" t={t} featured={focus==="planningManager"}/><h3>{t.planningAgents}</h3><div className="agent-grid">{planning.map(id=><AgentCard key={id} id={id} t={t}/>)}</div></section></div></div>}
function AgentCard({id,t,featured=false}:{id:Route;t:typeof text.en;featured?:boolean}){return <article className={`agent-card ${featured?"featured":""}`}><span className="chip neutral">Agent</span><h2>{nameFor(t,id)}</h2><small>{t.responsibilities}</small><p>{responsibility[id]}</p></article>}
const provisionAgents:Route[]=["cfo","controller","planningManager","ap","ar","treasury","assets","gl","tax","planning","pricing","value"];
function AdminWorkspace({t}:{t:typeof text.en}){const [selected,setSelected]=useState<Route[]>(provisionAgents);return <><div className="info security"><b>Production administration uses authenticated user identity.</b> A shared admin/admin credential is intentionally not exposed. Local bootstrap credentials must force a password change.</div><div className="two"><Panel title={t.companies}><div className="admin-form"><label>Company name<input placeholder="Company legal name"/></label><label>Tenant code<input placeholder="company-code"/></label><button className="primary">Onboard company</button></div></Panel><Panel title={t.users}><div className="admin-form"><label>Email<input type="email" placeholder="user@company.com"/></label><label>Role<select><option>Tenant administrator</option><option>Finance user</option><option>Reviewer</option></select></label><button className="primary">Invite user</button></div></Panel></div><Panel title={t.provision}><div className="provision-grid">{provisionAgents.map(id=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(s=>e.target.checked?[...s,id]:s.filter(x=>x!==id))}/><span><b>{nameFor(t,id)}</b><small>{responsibility[id]}</small></span></label>)}</div><div className="actionbar"><button className="primary">Provision selected agents</button></div></Panel><Hierarchy t={t} focus="admin"/></>}
function ErpWizard({t,existing,onSaved}:{t:typeof text.en;existing:Connection|null;onSaved:(c:Connection)=>void}){const [protocol,setProtocol]=useState(existing?.protocol||"json2"),[form,setForm]=useState({name:existing?.name||"",server:existing?.endpoint||"",database:existing?.database||"",login:existing?.login||"",key:"",company:existing?.company||""}),[result,setResult]=useState(""),[tested,setTested]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{if(existing)setForm(f=>({...f,name:existing.name,server:existing.endpoint,database:existing.database,login:existing.login,company:existing.company}))},[existing]);const set=(k:string,v:string)=>{setTested(false);setForm(f=>({...f,[k]:v}))};const request=async(path:string)=>{setBusy(true);try{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.name,endpoint:form.server,database:form.database,login:form.login,api_key:form.key,company:form.company,protocol})}),j=await r.json() as {ok?:boolean;message?:string;connection?:Connection};setResult(j.message||`HTTP ${r.status}`);if(path.endsWith("test"))setTested(!!j.ok);if(j.ok&&j.connection)onSaved(j.connection)}catch{setResult("Connection request failed.")}finally{setBusy(false)}};return <Panel title={t.connect}><div className="form grid-form"><label>Connection name<input value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Server URL<input placeholder="https://company.odoo.com" value={form.server} onChange={e=>set("server",e.target.value)}/></label><label>Database<input value={form.database} onChange={e=>set("database",e.target.value)}/></label><label>Login<input value={form.login} onChange={e=>set("login",e.target.value)}/></label><label>API key<input type="password" placeholder={existing?"Leave blank to keep saved key":"Required"} value={form.key} onChange={e=>set("key",e.target.value)}/></label><label>Protocol<select value={protocol} onChange={e=>{setProtocol(e.target.value);setTested(false)}}><option value="json2">JSON-2 (Odoo 19+)</option><option value="jsonrpc">JSON-RPC (Odoo 8–18)</option><option value="xmlrpc">XML-RPC (Odoo 8–18)</option></select></label><label>Odoo company<input value={form.company} onChange={e=>set("company",e.target.value)}/></label><div className="info">Credentials are encrypted and saved for this signed-in user and tenant. The API key is never returned to the browser. Draft creation remains subject to human review and posting.</div><div className="form-actions"><button disabled={busy||(!form.key&&!existing)} onClick={()=>request("/api/erp-connections/test")}>{t.test}</button><button className="primary" disabled={busy||(!tested&&!existing)} onClick={()=>request("/api/erp-connections")}>{t.save}</button></div>{result&&<div className="result" role="status">{result}</div>}</div></Panel>}
