"use client";

import { useEffect, useMemo, useState } from "react";
import "./modules.css";
import "./agents.css";
import { formatDate, formatMoney, getMessages, type Lang, type MessageKey, type Translation } from "./lib/i18n";

type AgentId="ap"|"treasury"|"assets"|"gl"|"tax";
type View="overview"|AgentId|"workflow"|"integrations";
type Agent={id:AgentId;icon:string;color:string;name:MessageKey;description:MessageKey;mission:MessageKey;controls:MessageKey[];references:MessageKey[];count:number};

const agents:Agent[]=[
  {id:"ap",icon:"AP",color:"teal",name:"apName",description:"apDescription",mission:"apMission",controls:["duplicateControl","matchControl","taxReviewControl"],references:["pcgo46","taxVatWithholding"],count:8},
  {id:"treasury",icon:"TR",color:"blue",name:"treasuryName",description:"treasuryDescription",mission:"treasuryMission",controls:["bankReconciliationControl","segregationControl","unusualPaymentControl"],references:["pcgo5","cashFlow"],count:6},
  {id:"assets",icon:"FA",color:"gold",name:"assetsName",description:"assetsDescription",mission:"assetsMission",controls:["capitalisationControl","componentControl","impairmentControl"],references:["pcgo28","componentsImpairment"],count:4},
  {id:"gl",icon:"GL",color:"violet",name:"glName",description:"glDescription",mission:"glMission",controls:["balanceControl","periodControl","subledgerControl"],references:["normalStatements","measurementRules"],count:12},
  {id:"tax",icon:"TX",color:"red",name:"taxName",description:"taxDescription",mission:"taxMission",controls:["scopeControl","vatControl","deadlineControl"],references:["cameroonTaxCode","taxScope"],count:5},
];

function initialLanguage():Lang{if(typeof window==="undefined")return"en";return localStorage.getItem("my-accountant-language")==="fr"?"fr":"en"}
function initialErp(){if(typeof window==="undefined")return{endpoint:"",mock:true};try{return JSON.parse(sessionStorage.getItem("erp-test-config")||"null")||{endpoint:"",mock:true}}catch{return{endpoint:"",mock:true}}}

export default function Home(){
  const [lang,setLang]=useState<Lang>(initialLanguage);const [view,setView]=useState<View>("overview");const [notice,setNotice]=useState("");const [query,setQuery]=useState("");
  const [erp]=useState(initialErp);const [endpoint,setEndpoint]=useState(erp.endpoint);const [token,setToken]=useState("");const [mock,setMock]=useState(erp.mock);
  const t=getMessages(lang);const selected=agents.find(a=>a.id===view);const filtered=useMemo(()=>agents.filter(a=>(t[a.name]+t[a.description]).toLocaleLowerCase().includes(query.toLocaleLowerCase())),[query,t]);
  useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem("my-accountant-language",lang)},[lang]);
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),2800)};
  const save=()=>{sessionStorage.setItem("erp-test-config",JSON.stringify({endpoint,mock}));flash(t.connected)};
  const test=async()=>{if(mock||!endpoint){flash(t.connected);return}try{const response=await fetch(endpoint.replace(/\/$/,"")+"/health",{headers:token?{Authorization:`Bearer ${token}`}:{}});flash(response.ok?t.connected:`HTTP ${response.status}`)}catch{flash(t.connectionFailed)}};
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><span><b>{t.product}</b><small>{t.subtitle}</small></span></div><div className="company-switch"><span className="company-avatar">AK</span><span><b>Akwa Consulting</b><small>{t.companyContext}</small></span></div><nav><p className="nav-label">{t.navAgents}</p><Nav active={view==="overview"} icon="⌂" label={t.overview} onClick={()=>setView("overview")}/>{agents.map(a=><Nav key={a.id} active={view===a.id} icon={a.icon} label={t[a.name]} count={a.count} onClick={()=>setView(a.id)}/>)}<p className="nav-label">{t.navControl}</p><Nav active={view==="workflow"} icon="✓" label={t.journalCentre} count={3} onClick={()=>setView("workflow")}/><Nav active={view==="integrations"} icon="↔" label={t.erpConnector} onClick={()=>setView("integrations")}/></nav><div className="sidebar-foot"><div className="sync"><span className="pulse"/><span><b>SYSCOHADA + CGI 2025</b><small>{t.frameworksLoaded}</small></span></div><div className="profile"><span>NS</span><div><b>Nadia Simo</b><small>{t.approver}</small></div></div></div></aside><section className="workspace"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">M</span><b>{t.product}</b></div><label className="search">⌕<input aria-label={t.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><div className="top-actions"><button className="lang" onClick={()=>setLang(lang==="en"?"fr":"en")}>{t.switchLanguage}</button><button className="icon-button notification" aria-label={t.notifications}>●<i>3</i></button></div></header>{view==="overview"&&<Overview t={t} agents={filtered} setView={setView}/>} {selected&&<AgentPage t={t} agent={selected} flash={flash}/>} {view==="workflow"&&<Workflow t={t} lang={lang} flash={flash}/>} {view==="integrations"&&<Integrations t={t} endpoint={endpoint} setEndpoint={setEndpoint} token={token} setToken={setToken} mock={mock} setMock={setMock} save={save} test={test}/>}</section>{notice&&<div className="toast"><span>✓</span>{notice}</div>}</main>;
}

function Nav({active,icon,label,count,onClick}:{active:boolean;icon:string;label:string;count?:number;onClick:()=>void}){return <button className={`nav-item ${active?"active":""}`} onClick={onClick}><span>{icon}</span>{label}{count!==undefined&&<em>{count}</em>}</button>}
function Overview({t,agents,setView}:{t:Translation;agents:Agent[];setView:(v:View)=>void}){return <div className="content"><div className="module-heading"><p>{t.product.toUpperCase()}</p><h1>{t.greeting}</h1><span>{t.introduction}</span></div><div className="agent-grid">{agents.map((a,index)=><button className={`agent-card ${a.color}`} key={a.id} onClick={()=>setView(a.id)}><div className="agent-head"><span className="agent-icon">{a.icon}</span><em>{String(index+1).padStart(2,"0")}</em></div><h2>{t[a.name]}</h2><p>{t[a.description]}</p><div className="agent-stats"><span><b>{a.count}</b><small>{t.toProcess}</small></span><span><b>{Math.max(2,a.count-2)}</b><small>{t.ready}</small></span><span><b>{index%3}</b><small>{t.exceptions}</small></span></div><footer>{t.openAgent}<b>→</b></footer></button>)}</div><section className="module-security"><span>✓</span><div><b>{t.complianceTitle}</b><p>{t.complianceText}</p></div><button onClick={()=>setView("workflow")}>{t.journalCentre} →</button></section></div>}
function AgentPage({t,agent,flash}:{t:Translation;agent:Agent;flash:(s:string)=>void}){return <div className="content inner"><div className="page-heading"><div><p>{t.navAgents}</p><h1>{t[agent.name]}</h1><p className="subtitle">{t[agent.mission]}</p></div><button className="primary" onClick={()=>flash(t.addedToQueue)}>＋ {t.newTransaction}</button></div><div className="agent-layout"><section className="panel"><div className="panel-head"><div><h2>{t.workQueue}</h2><p>{t.toProcess}: {agent.count}</p></div></div>{["AFR-2026-0842","BANK-REC-0731","CLOSE-2026-07"].map((id,index)=><button className="work-item" key={id}><span className={`work-badge ${agent.color}`}>{agent.icon}</span><div><b>{id}</b><small>{index===0?t.sampleSupplier:t.sampleEntity}</small></div><em className={`status ${index?"blue":"amber"}`}>{index?t.statusReady:t.statusAnomaly}</em><strong>→</strong></button>)}</section><div className="agent-side"><InfoPanel title={t.purposeControls} values={agent.controls.map(k=>t[k])} kind="check"/><InfoPanel title={t.appliedReferences} values={agent.references.map(k=>t[k])} kind="reference"/></div></div><AgentOutput t={t} agent={agent}/></div>}
function InfoPanel({title,values,kind}:{title:string;values:string[];kind:"check"|"reference"}){return <section className="panel detail-panel"><div className="panel-head"><h2>{title}</h2></div>{values.map(value=><p className={kind} key={value}><span>{kind==="check"?"✓":"§"}</span>{value}</p>)}</section>}
function AgentOutput({t,agent}:{t:Translation;agent:Agent}){const rows:[[string,string]]=[ [t.summary,t.outputSummary] ] as [[string,string]];const more=[[t.recommendedAction,t.outputAction],[t.assumptions,t.outputAssumption],[t.accountingTreatment,t.outputAccounting],[t.taxTreatment,t.outputTax],[t.controlsPerformed,agent.controls.map(k=>t[k]).join(" · ")],[t.sourceReferences,agent.references.map(k=>t[k]).join(" · ")],[t.confidence,"94%"],[t.approvalRequired,t.yes]];return <section className="panel agent-output"><div className="panel-head"><h2>{t.agentOutput}</h2><em className="balanced">{t.draftOnly}</em></div>{[...rows,...more].map(([label,value])=><div className="output-row" key={label}><b>{label}</b><span>{value}</span></div>)}</section>}
function Workflow({t,lang,flash}:{t:Translation;lang:Lang;flash:(s:string)=>void}){const lines=[{account:"604100",label:t.purchasesSupplies,debit:1200000,credit:0},{account:"445200",label:t.recoverableVat,debit:231000,credit:0},{account:"401100",label:t.supplierPayable,debit:0,credit:1431000}];return <div className="content inner"><div className="page-heading"><div><p>{t.navControl}</p><h1>{t.journalCentre}</h1><p className="subtitle">{t.controlledChain}</p></div><button className="primary" onClick={()=>flash(t.draftCreated)}>{t.submitDraft}</button></div><div className="handoff"><Step code="AP" label={t.coding}/><i>→</i><Step code="TX" label={t.taxReview}/><i>→</i><Step code="GL" label={t.accountingControl}/><i>→</i><Step code="NS" label={t.approval}/><i>→</i><Step code="ERP" label={t.erpDraft}/></div><section className="panel journal-panel"><div className="panel-head"><div><h2>{t.proposedJournal} · FAC-2026-0842</h2><p>{t.purchaseJournal} · {formatDate(new Date("2026-07-31T00:00:00Z"),lang)} · XAF</p></div><em className="balanced">✓ {t.balanced}</em></div><div className="journal-head"><span>{t.account}</span><span>{t.description}</span><span>{t.debit}</span><span>{t.credit}</span></div>{lines.map(line=><div className="journal-line" key={line.account}><b>{line.account}</b><span>{line.label}</span><strong>{line.debit?formatMoney(line.debit,lang):"—"}</strong><strong>{line.credit?formatMoney(line.credit,lang):"—"}</strong></div>)}<div className="journal-total"><span>{t.totals}</span><b>{formatMoney(1431000,lang)}</b><b>{formatMoney(1431000,lang)}</b></div></section><div className="ai-note"><span>✦</span><div><b>{t.crossChecks}</b><p>{t.crossChecksDetail}</p></div></div></div>}
function Step({code,label}:{code:string;label:string}){return <span><b>{code}</b><small>{label}</small></span>}
function Integrations({t,endpoint,setEndpoint,token,setToken,mock,setMock,save,test}:{t:Translation;endpoint:string;setEndpoint:(s:string)=>void;token:string;setToken:(s:string)=>void;mock:boolean;setMock:(v:boolean)=>void;save:()=>void;test:()=>void}){return <div className="content inner"><div className="page-heading"><div><p>{t.navControl}</p><h1>{t.connectorTitle}</h1><p className="subtitle">{t.connectorIntro}</p></div></div><div className="connector-grid"><section className="panel connector-form"><label>{t.apiUrl}<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="https://sandbox.erp.example/api/v1" disabled={mock}/></label><label>{t.authMethod}<select disabled={mock}><option>Bearer token</option><option>OAuth 2.0</option><option>API key</option><option>Basic</option></select></label><label>{t.testToken}<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="••••••••••••" disabled={mock}/></label><label className="checkline"><input type="checkbox" checked={mock} onChange={e=>setMock(e.target.checked)}/>{t.simulator}</label><div className="form-actions"><button className="outline" onClick={test}>{t.testConnection}</button><button className="primary" onClick={save}>{t.save}</button></div></section><section className="panel api-contract"><div className="panel-head"><h2>{t.journalContract}</h2></div><code>{`POST /journals/drafts\n{\n  "external_id": "FAC-2026-0842",\n  "ledger": "ACH",\n  "currency": "XAF",\n  "posting_status": "DRAFT",\n  "lines": [ ... ],\n  "approvals": [ ... ],\n  "evidence": [ ... ]\n}`}</code><p>✓ Idempotency-Key · ✓ OAuth/API key · ✓ Audit trail</p></section></div><div className="mock-banner"><span>i</span><div><b>{mock?t.simulatorActive:t.externalSelected}</b><p>{t.secretWarning}</p></div></div></div>}
