"""add operations and email tables

Revision ID: edda78563138
Revises: 1625f8eeca76
"""
from alembic import op
import sqlalchemy as sa


revision = 'edda78563138'
down_revision = '1625f8eeca76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_correlation_id'), 'background_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_kind'), 'background_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_background_jobs_record_id'), 'background_jobs', ['record_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_background_jobs_tenant_id'), 'background_jobs', ['tenant_id'], unique=False)
    op.create_table('inbound_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id')
    )
    op.create_index(op.f('ix_inbound_emails_status'), 'inbound_emails', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_emails_tenant_id'), 'inbound_emails', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inbound_emails_tenant_id'), table_name='inbound_emails')
    op.drop_index(op.f('ix_inbound_emails_status'), table_name='inbound_emails')
    op.drop_table('inbound_emails')
    op.drop_index(op.f('ix_background_jobs_tenant_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_record_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_kind'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_correlation_id'), table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
